//=====-- PIC16Subtarget.h - Define Subtarget for the PIC16 ---*- C++ -*--====//
//
//                     The LLVM Compiler Infrastructure
//
// This file is distributed under the University of Illinois Open Source 
// License. See LICENSE.TXT for details.
//
//===----------------------------------------------------------------------===//
//
// This file declares the PIC16 specific subclass of TargetSubtarget.
//
//===----------------------------------------------------------------------===//

#ifndef PIC16SUBTARGET_H
#define PIC16SUBTARGET_H

#include "llvm/CodeGen/TargetSubtargetInfo.h"

#define GET_SUBTARGETINFO_HEADER
#include "PIC16GenSubtargetInfo.inc"

#include <string>

namespace llvm {

class PIC16TargetMachine;

class PIC16Subtarget : public PIC16GenSubtargetInfo {

  // IsCooper - Target ISA is Cooper.
  bool IsCooper;

public:
  /// This constructor initializes the data members to match that
  /// of the specified triple.
  ///
  PIC16Subtarget(const Triple &TT, const std::string &CPU,
          const std::string &FS, const PIC16TargetMachine &TM, bool Cooper = false);
  
  /// isCooper - Returns true if the target ISA is Cooper.
  bool isCooper() const { return IsCooper; }

  /// ParseSubtargetFeatures - Parses features string setting specified 
  /// subtarget options.  Definition of function is auto generated by tblgen.
  void ParseSubtargetFeatures(StringRef CPU, StringRef TuneCPU, StringRef FS);

  // The following are methods added in new LLVM, all of which we assume to return false

};
} // End llvm namespace

#endif  // PIC16SUBTARGET_H
