[package]
name = "picalculator_complex_stm"
version = "0.1.0"
edition = "2024"

[dependencies]
cortex-m = "0.7.7"
cortex-m-rt = "0.7.5"
stm32f4xx-hal = { version = "0.22.1", features = ["stm32f401"] }
rtt-target = { version= "0.6.1", features = [] }
panic-halt = "1.0.0"
